### ISSUE TITLE
_header.html.erb

### ISSUE THREAD

**Issue by patrickf3139** [GracepointMinistries/GraceTunes#11]
@josephli036 @leethomas Hey guys, does it make sense for this file to be under views/layouts directory? It's not really a layout but really a partial right? I think it makes more sense it to be under views/application.

**Comment by natyconnor** [comment]
Yeah, that's the standard: https://robots.thoughtbot.com/directory-for-shared-partials-in-rails

Also lets you do `render header` rather than `render <folder>/header`

**Comment by patrickf3139** [comment]
Lol didn't think you would comment on this issue. Thanks Nathan! Adding this to our bugfixes list.

**Comment by natyconnor** [comment]
Haha, yeah I'm gonna try and get a handle on what the code is doing today since I'm free for the afternoon. May have some questions for you.

**Comment by patrickf3139** [comment]
Cool, I don't think it'll take long you too long (so many people were busy or out during GTS we only merged 5 PRs). Are you planning on contributing? I'm guessing you have a lot of vested interest in this being on the praise band huh?

**Comment by natyconnor** [comment]
I'd like to, though it might be limited to comments for now with welcome week coming up. Definitely want to work out some of the architecture looking forward, for things like transposing songs and set history. Maybe I'll put some of my thoughts in a wiki page or something (as in github wiki).

**Comment by patrickf3139** [comment]
Ok I'll get you added to the repo! This project is about to get put on the back-burner and we also have a ton of features planned even after we finish the basic app so we won't be done for a long time, plenty of time to contribute. Thanks for all your help so far!

**Comment by leethomas** [comment]
closed by https://github.com/GracepointMinistries/GraceTunes/pull/13
