### ISSUE TITLE
Domain change

### ISSUE THREAD

**Issue by PatrickF1** [GracepointMinistries/GraceTunes#155]
Hi @paulosliu @jbchen120, when the email address changes from gpmail.org to acts2.network, we will have an outage because of this line https://github.com/GracepointMinistries/GraceTunes/blob/master/config/initializers/omniauth.rb#L3. We should avert that by updating it to check both, but I'm not sure how.

My original PR has some documentation that might be of help https://github.com/GracepointMinistries/GraceTunes/pull/28. Let me know if you guys can't get to it. I'll contact Michael Kang to get an idea of when the switch will happen.

**Comment by paulosliu** [comment]
Ok I'll try to look into it soon.

**Comment by PatrickF1** [comment]
Taking notes here for posterity (and so everyone can learn and take more ownership over this)...

I was going to attempt to allow both gpmail.org and acts2.network simultaneously which seemed possible because the Ruby gem says this: 
![Screenshot 2023-08-20 at 5 55 10 PM](https://github.com/GracepointMinistries/GraceTunes/assets/1967248/d09d03cb-84e2-460c-bb9f-cd9eb4172e7d)

However, after doing further research (but not testing it myself), I don't think it's possible:
- https://stackoverflow.com/questions/52868276/pass-multiple-domains-to-restrict-in-hd-parameter-in-google-oauth#comment131319848_54343998
- https://github.com/thephpleague/oauth2-google/issues/62
- https://github.com/zquestz/omniauth-google-oauth2/issues/374

So, the two options are now
1. change `hd` from `gpmail.org` to `acts2.network`, merge, and prepare a build. When the switch over happens, immediately deploy for minimal downtime
2. stop using `hd` and do the domain check here instead https://github.com/GracepointMinistries/GraceTunes/blob/master/app/controllers/sessions_controller.rb#L13, throwing an error if domain not in those two domains. The main downside of this is that the UI for logging in will no longer be filtered to only show the GP login and will show all the Gmail logins. Also, it'll take require some testing and thus resetting up my dev environment.

Unfortunately, I don't think I have time to do (2) so I'm leaning towards (1).

**Comment by PatrickF1** [comment]
Another complication with either options is we will need to translate the new emails to the old emails for permission lookup so people who can create / edit songs don't lose that power until we can do a DB migration.
